# This workflow will pass tests of module passed by input

name: som_plantmeter
on:
  workflow_dispatch:
  pull_request: # PR
jobs:
  erp-tests-module:
    uses: Som-Energia/openerp_som_addons/.github/workflows/reusable_workflow.yml@main
    with:
      module: som_modules_fulla
    secrets:
      ACCESS_TOKEN_GA: ${{ secrets.ACCESS_TOKEN_GA }}
      ESIOS_TOKEN: ${{ secrets.ESIOS_TOKEN }}
      SRID: ${{ secrets.SRID }}
